import { createBuildSection } from './build-section.js';
import { createResultsSection } from './results-section.js';
import { createServerSection } from './server-section.js';
import { createSettingsSection } from './settings-section.js';

import type { ScreenId } from '../state/app-state.js';
import type { SectionDefinition, SectionRegistryContext } from './types.js';

export function createSectionRegistry(context: SectionRegistryContext): Record<ScreenId, SectionDefinition> {
    const {
        t,
        locale,
        form,
        setForm,
        uiMode,
        setLocale,
        setUiMode,
        showHints,
        setShowHints,
        session,
        compact,
        latestBuildDir,
        selectedRunField,
        setSelectedRunField,
        serverForm,
        setServerForm,
        serverState,
        serverDoctor,
        installServerCore,
        useLatestBuildForServer,
        applyServerEntrypointToValidation,
        launchServer,
        stopServer,
        clearServerLogs,
        selectedServerField,
        setSelectedServerField,
        presets,
        selectedPreset,
        selectedPresetId,
        setSelectedPresetId,
        applySelectedPreset,
        createPreset,
        updateSelectedPreset,
        deleteSelectedPreset,
        selectedReportRunId,
        setSelectedReportRunId,
        selectedReportEntry,
        selectedReport,
        allResultModItems = [],
        resultModItems,
        resultModDisputedCount = 0,
        selectedResultMod,
        selectedResultModReviewState = null,
        selectedResultModId,
        setSelectedResultModId,
        saveSelectedResultModOverride = () => {},
        confirmSelectedResultModOverride = () => {},
        clearSelectedResultModOverride = () => {},
        resultModsDisputedOnly,
        setResultModsDisputedOnly,
        resultModsSortMode,
        setResultModsSortMode,
        reportHistory,
        reviewItems,
        selectedReviewItem,
        selectedReviewItemId,
        setSelectedReviewItemId,
        saveReviewOverride,
        clearReviewOverride,
        reviewOverridesPath,
        reviewNotice,
        selectedSettingsField,
        setSelectedSettingsField,
        selectedAuthorId,
        setSelectedAuthorId,
        onInteractionChange,
        onRun
    } = context;

    return {
        build: createBuildSection({
            t,
            form,
            uiMode,
            session,
            selectedRunField,
            presets,
            selectedPreset,
            selectedPresetId,
            compact,
            onChange: setForm,
            onRun,
            onInteractionChange,
            onSelectedFieldChange: setSelectedRunField,
            onSelectedPresetIdChange: setSelectedPresetId,
            onApplyPreset: applySelectedPreset,
            onCreatePreset: createPreset,
            onUpdatePreset: updateSelectedPreset,
            onDeletePreset: deleteSelectedPreset
        }),
        server: createServerSection({
            t,
            form: serverForm,
            serverState,
            doctorState: serverDoctor,
            latestBuildDir,
            selectedRunLabel: selectedReport?.run.runId || selectedReportEntry?.runId || null,
            selectedServerField,
            onChange: setServerForm,
            onUseLatestBuild: useLatestBuildForServer,
            onInstallCore: installServerCore,
            onApplyEntrypointToValidation: applyServerEntrypointToValidation,
            onLaunchServer: launchServer,
            onStopServer: stopServer,
            onClearLogs: clearServerLogs,
            onInteractionChange,
            onSelectedFieldChange: setSelectedServerField
        }),
        results: createResultsSection({
            t,
            form,
            session,
            compact,
            reportHistory,
            selectedReportRunId,
            selectedReportEntry,
            selectedReport,
            allResultModItems,
            resultModItems,
            resultModDisputedCount,
            selectedResultMod,
            selectedResultModReviewState,
            selectedResultModId,
            onSelectedResultModIdChange: setSelectedResultModId,
            onSaveSelectedResultModOverride: saveSelectedResultModOverride,
            onConfirmSelectedResultModOverride: confirmSelectedResultModOverride,
            onClearSelectedResultModOverride: clearSelectedResultModOverride,
            resultModsDisputedOnly,
            onResultModsDisputedOnlyChange: setResultModsDisputedOnly,
            resultModsSortMode,
            onResultModsSortModeChange: setResultModsSortMode,
            onSelectedReportRunIdChange: setSelectedReportRunId,
            reviewOverridesPath,
            reviewNotice
        }),
        settings: createSettingsSection({
            t,
            locale,
            form,
            setForm,
            uiMode,
            setLocale,
            setUiMode,
            showHints,
            setShowHints,
            session,
            compact,
            selectedSettingsField,
            onSelectedSettingsFieldChange: setSelectedSettingsField,
            selectedAuthorId,
            onSelectedAuthorIdChange: setSelectedAuthorId,
            onInteractionChange
        })
    };
}
